#-------------------------------
# Site Settings
title: Pudim Perfeito
logo: "https://i1.wp.com/pudimperfeito.50x.com.br/images/logo-pudim-perfeito.png?resize=200,77" # You can add own logo. For example '/images/logo.png'.
description: Seja bem-vinda ao Pudim Perfeito, o seu portal para um universo de delícias cremosas e irresistíveis!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pudimperfeito.50x.com.br" # the base hostname & protocol for your site, e.g. http://example.com
cdnurl: "https://i2.wp.com/drive.50x.com.br/pudimperfeito" # the base hostname & protocol for your site, e.g. http://cdn.example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: Pudim perfeito
  author__bio: Doce Pecado que te Leva ao Paraíso! A textura cremosa, a calda irresistível... Experimente a felicidade em cada mordida!
  author__avatar: 'https://i0.wp.com/pudimperfeito.50x.com.br/favicon.png?resize=128,128'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/geanramos"}
- {icon: "ion-logo-facebook", link: "https://facebook.com/geanramoss"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/geanramus"}
- {icon: "ion-logo-youtube", link: "https://youtube.com/@geanramos"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Pudim Perfeito
  hero__description: Descubra receitas, dicas e truques para preparar o pudim dos seus sonhos! Do clássico ao gourmet, explore um universo de sabores e texturas que vão te conquistar.
  hero__image: 'https://i2.wp.com/drive.50x.com.br/pudimperfeito/images/03.jpg?resize=554,312'


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: pudimperfeito.50x.com.br/pv/ # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Digite seu melhor E-mail
mailchimp__button__text: Baixa Agora!

#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Os Melhores Pudins
  gallery__columns: 3
  gallery__images:
    - alt: 'pudim de leite condensado'
      url: 'https://i0.wp.com/pudimperfeito.50x.com.br/images/46388.jpg?resize=1000,562.5'
    - alt: 'pudim de pão'
      url: 'https://i0.wp.com/pudimperfeito.50x.com.br/images/46412.jpg?resize=1000,562.5'
    - alt: 'pudim de leite'
      url: 'https://i0.wp.com/pudimperfeito.50x.com.br/images/83618.jpg?resize=1000,562.5'
    - alt: 'pudim de geladeira'
      url: 'https://i0.wp.com/pudimperfeito.50x.com.br/images/29900.jpg?resize=1000,562.5'
    - alt: 'receita de pudim de leite condensado'
      url: 'https://i0.wp.com/pudimperfeito.50x.com.br/images/29263.jpg?resize=1000,562.5'
    - alt: 'pudim de leite em pó'
      url: 'https://i0.wp.com/pudimperfeito.50x.com.br/images/46291.jpg?resize=1000,562.5'
    - alt: 'receita de pudim de leite condensado'
      url: 'https://i0.wp.com/pudimperfeito.50x.com.br/images/02748.jpg?resize=1000,562.5'
    - alt: 'receita de pudim'
      url: 'https://i0.wp.com/pudimperfeito.50x.com.br/images/46362.jpg?resize=1000,562.5'
    - alt: 'como fazer pudim'
      url: 'https://i0.wp.com/pudimperfeito.50x.com.br/images/pudim-top.jpg?resize=1000,562.5'


#-------------------------------
# Contact Settings
contact:
  email: geanramus@gmail.com # Add your email for contant form
  description: Menso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: geanramos # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - kramdown-parser-gfm

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
